# Tier 2 · Advanced — Systematic Trader (10 weeks x 2 sessions) and Tier 3 · Expert — Quant Desk (20 weeks x 1 session).
# Structure and copy from Master Curriculum v2 (28 Aug 2026). Sessions ship unpublished (draft) until full content + quizzes are authored.
# Fields: (week, day, title_en, title_hi, concept, ai_lab, psychology, strategy, topics_hi, kaam, outcome, tools, fun, compliance)

T2_WEEKS = [
 ("Stack aur prompts", "Your systematic stack and prompts"),
 ("Structure aur VWAP reversion", "Market structure and VWAP reversion"),
 ("Options chain aur credit spread", "Options chain and credit spreads"),
 ("Iron condor aur hedging", "Iron condor and hedging"),
 ("Swing system aur NR7", "Swing system and NR7"),
 ("Momentum aur portfolio risk", "Momentum rotation and portfolio risk"),
 ("Algo Level 2 deploy", "Algo Level 2 deployment"),
 ("Backtest Level 2 aur overfitting", "Backtest Level 2 and overfitting"),
 ("Sprint review aur events", "Sprint review and events"),
 ("Business plan aur capstone", "Business plan and capstone"),
]
T2 = [
 (1,1,"Systematic trader's stack","Systematic Trader Ka Stack","Algo Level 2 setup","Stack setup","Tool ka moh","Setup",
  "Tier 1 recap; SEBI algo framework deep-dive; tool stack: Claude Projects, ek no-code platform (student ki choice, paper mode), broker API basics.",
  "Apna stack set karo: Claude Project + 1 no-code platform (paper mode) + journal.","Aapka connected research + paper-execution stack ready hoga.",["Claude","No-code platform (koi bhi)","Broker"],"Lab 1: Platform onboarding, paper mode ON.","Platform empanelment status verified before any platform is named."),
 (1,2,"Prompt engineering for traders","Prompt Engineering for Traders","AI Level 2","10-prompt library","Over-reliance",None,
  "Structured prompts, JSON outputs, Claude as checklist enforcer, devil's-advocate prompt, hallucination guards, reusable prompt library.",
  "10-prompt Trading Prompt Library banao (screen, plan, review, risk-check).","Aap AI se consistent, verifiable output nikaal paoge.",["Claude"],None,"AI-usage disclosure."),
 (2,1,"Multi-timeframe TA and market structure","Multi-Timeframe TA + Market Structure","TA Level 2","Confluence scorer","Complexity bias",None,
  "HTF bias, LTF entry; BOS/CHoCH, liquidity sweeps, VWAP bands, volume profile basics; confluence scoring.",
  "MTF checklist + AI 'confluence scorer' prompt.","Aap 3 timeframes ko ek framework mein padh paoge.",["Chart","Claude"],None,None),
 (2,2,"Strategy #1: VWAP mean-reversion (intraday)","Strategy #1: VWAP Mean-Reversion (Intraday)","Strategy #1 · Algo L2","No-code build","Trend-day ka darr","VWAP Mean-Reversion",
  "VWAP se extension (bands), reversal trigger, target = VWAP, ATR SL, time window 10:00-2:30; index futures proxy ya liquid stocks.",
  "Rules ko no-code strategy builder mein paper mode par chalao.","Aapki pehli no-code strategy paper mein chal rahi hogi.",["No-code platform"],"Lab 2: Build VWAP strategy in no-code.","No return claims."),
 (3,1,"Options deep-dive: Greeks, IV, chain (NISM-grounded)","Options Deep-Dive: Greeks, IV, Chain","Options Level 2","Chain Reader prompt","IV ka bhram",None,
  "Delta/Gamma/Theta/Vega intuition, IV vs HV, IV rank, India VIX, option chain: OI build-up, PCR, max pain; expiry dynamics.",
  "Daily 'Chain Reader' prompt: AI se OI/PCR summary, khud verify.","Aap option chain se market positioning padh paoge.",["Broker chain","Claude"],None,"NISM ground-truth required."),
 (3,2,"Strategy #2: directional credit spread","Strategy #2: Directional Credit Spread (Bull Put / Bear Call)","Strategy #2","Backtester read","Premium ka lalach","Directional Credit Spread",
  "Weekly NIFTY, HTF bias + IV rank filter, strike selection (delta 15-25), max loss defined, exit at 50% profit / 2x loss / 1 DTE.",
  "Options backtester par 2-3 saal ka backtest; rules card.","Aap defined-risk directional options strategy chala paoge.",["Options backtester","Claude"],"Lab 3: Backtest credit spread, read report.","'Past performance' clause; margin explained."),
 (4,1,"Strategy #3: defined-risk iron condor (expiry week)","Strategy #3: Defined-Risk Iron Condor","Strategy #3","Adjustment rules","Income ka bhram","Iron Condor",
  "Non-directional, IV-rank high, wings for defined loss, adjustment rules (roll tested side), event-avoid rule.",
  "Backtest + paper deploy in no-code.","Aap non-directional strategy risk ke saath samjhoge.",["Options backtester","No-code"],None,"No 'income assured' language."),
 (4,2,"Futures, margin and hedging via AI","Futures, Margin & Hedging via AI","Hedging Level 2","Hedge planner","Overnight gap ka darr",None,
  "Futures pricing/basis, SPAN + exposure margin, MTM, rollover; portfolio hedge with index puts/futures; weekly F&O planning workflow.",
  "Apne (paper) swing portfolio ka hedge plan AI se banwao.","Aap portfolio-level hedge design kar paoge.",["Broker margin calculator","Claude"],"Lab 4: Margin calculator + hedge sizing.","Verified SEBI framework references."),
 (5,1,"Strategy #4: MTF EMA pullback swing (system) + stock selection","Strategy #4: MTF EMA Pullback Swing (System)","Strategy #4","Forensic quick-check","Story bias","MTF EMA Pullback Swing",
  "Tier 1 strategy ko full system: weekly trend filter, daily pullback, RS vs NIFTY, position limits; 1-session fundamental filter (debt, pledge, cash flow, Piotroski-lite).",
  "Screener (Chartink/AI) + fundamental filter se 10-stock swing list.","Aap stock selection ko system bana paoge.",["Chartink","screener.in","Claude"],None,"No fair-value / target language."),
 (5,2,"Strategy #5: NR7 / inside-bar breakout with ATR stops","Strategy #5: NR7 / Inside-Bar Breakout","Strategy #5","NR7 scanner","Whipsaw ka darr","NR7 / Inside-Bar Breakout",
  "Volatility contraction/expansion, NR7/inside-bar detection, breakout entry, ATR trailing stop, holding 2-10 din.",
  "No-code screener + alert; paper deploy.","Aap volatility-compression setups trade kar paoge.",["No-code platform","Chartink"],"Lab 5: NR7 scanner build.",None),
 (6,1,"Strategy #6: momentum rotation (top-N monthly)","Strategy #6: Momentum Rotation (Top-N Monthly)","Strategy #6","Momentum screener","Momentum crash","Momentum Rotation",
  "Cross-sectional momentum: 1/3/6/12-month returns composite, top-N from NIFTY 500, monthly rebalance, regime filter (NIFTY > 200 DMA).",
  "Momentum screener (AI-assisted) chalao; paper portfolio sheet.","Aap ek rules-based portfolio strategy chala paoge.",["Claude","Google Sheets"],None,None),
 (6,2,"Position sizing, portfolio heat and correlation","Position Sizing, Portfolio Heat & Correlation","Risk Level 2","Risk dashboard","Correlation trap",None,
  "Fixed-fractional vs volatility sizing, portfolio heat (total open risk), correlation trap, max positions, drawdown-based throttling.",
  "Portfolio risk dashboard sheet (open risk, heat, correlation).","Aap poore portfolio ka risk ek number mein dekh paoge.",["Google Sheets","Claude"],"Lab 6: Risk dashboard.",None),
 (7,1,"Algo Level 2: no-code deployment + compliance","Algo Level 2: No-Code Deployment + Compliance","Algo Level 2","Deployment checklist","Automation bias","All 6 (paper)",
  "Strategy builder deep-dive, paper vs live modes, broker connect, Algo-ID tagging, order-rate limits, logs; kab no-code platform compliant hai/nahi.",
  "6 strategies paper-mode mein deploy; deployment checklist.","Aap compliant no-code deployment kar paoge.",["No-code platform","Broker"],"Lab 7: Deploy all 6 in paper.","Broker-as-principal; unregistered providers barred."),
 (7,2,"Pine Script for traders (optional track)","Pine Script for Traders (Optional)","Algo Level 2 (optional)","Pine strategy draft","Copy-paste ka khatra",None,
  "strategy() basics, entries/exits, strategy tester report, alerts webhook to no-code bridge; community scripts safely padhna.",
  "1 strategy (VWAP ya NR7) Pine mein likho (Claude-assisted).","Aap Pine strategy padh/likh/backtest kar paoge.",["TradingView charting/Pine (optional)","Claude"],None,"Optional; only for students already on TradingView."),
 (8,1,"Backtest Level 2: reading the report","Backtest Level 2: Report Padhna Seekho","Backtest Level 2","Scorecard","Sharpe ka moh",None,
  "Sharpe/Sortino/Calmar, max DD & duration, profit factor, expectancy, trade count; in-sample vs out-of-sample; slippage + cost model.",
  "Apne 6 backtests ka scorecard + cost-adjusted returns.","Aap backtest report ko critically padh paoge.",["Backtester reports","Claude"],"Lab 8: Cost-adjust all backtests.","'Past performance' clause."),
 (8,2,"Overfitting lab: spotting 'too good'","Overfitting Lab: 'Too Good' Kaise Pehchane","Validation Level 2","Parameter heatmap","Curve-fit ka lalach",None,
  "Parameter sweeps, curve-fitting, look-ahead bias, survivorship, trials ledger intro; robustness heatmap.",
  "1 strategy ka parameter heatmap + trials ledger.","Aap overfit strategy pehchan paoge.",["Backtester","Google Sheets","Claude"],None,None),
 (9,1,"4-week paper sprint review + AI EOD review","4-Week Paper Sprint Review + AI EOD Review","Trade Mgmt Level 2","Sprint scorecard","Live vs backtest gap",None,
  "Live paper results vs backtest expectation, rule-adherence audit, AI EOD market wrap + personal review workflow.",
  "Weekly review template (AI-driven) + sprint scorecard.","Aap live vs backtest gap ko diagnose kar paoge.",["Platform logs","Claude"],"Lab 9: Sprint review clinic.",None),
 (9,2,"Event trading + expiry-day playbook","Event Trading + Expiry-Day Playbook","Risk Level 2","Event rule-set","Event ka josh",None,
  "Results season, RBI/Fed, Budget, index expiry days: volatility behaviour, strategy pause/resume rules, gap risk on overnight options.",
  "Event rule-set added to all 6 strategies.","Aap events ko system ka part bana paoge.",["Calendar","Claude"],None,None),
 (10,1,"Trading business plan","Trading Business Plan","Business plan","One-page plan","Hobby vs business",None,
  "Capital allocation, drawdown limits, kill-switch rules, taxes (STT, F&O business income basics, rates verified in class), record-keeping, costs.",
  "One-page Trading Business Plan.","Aap trading ko business ki tarah plan karoge.",["Google Docs","Claude"],"Lab 10: Capstone prep.","Tax content is general education; CA consult advised. Rates never printed."),
 (10,2,"Capstone + certification","Capstone + Certification","Capstone","Capstone deck","Ownership",None,
  "Present 1 strategy: rules, backtest, cost-adjusted stats, 4-week paper results, what broke; peer Q&A; certificate; Tier 3 roadmap.",
  "Capstone deck (template provided).","Aap end-to-end systematic strategy present kar chuke honge.",[],None,"Certificate carries credential line + full disclaimer."),
]

T3_PHASES = {1:"P1 Foundation",2:"P2 Strategy Factory",3:"P3 Options Quant",4:"P4 Validation Lab",5:"P5 Risk & Deployment",6:"P6 Capstone"}
T3 = [
 (1,1,"Python for traders (Claude Code assisted)","Python for Traders","Algo Level 3 setup","Notebook: data + indicators","Tool anxiety",None,"Python basics for trading, pandas OHLC, resampling, indicators from scratch, Jupyter; Claude Code as pair-programmer.","Notebook: NIFTY data load + indicators plot.","Aap trading data Python mein handle kar paoge.",["Python","pandas","Claude Code"],None,None),
 (2,1,"Broker API + data pipeline","Broker API + Data Pipeline","Algo Level 3","Adapter pattern","Vendor lock-in",None,"Broker APIs (student's broker): auth, historical data, websocket ticks, order placement (sandbox/paper), rate limits; local data store (Parquet/SQLite).","Reusable data pipeline module (any-broker adapter).","Aapka data pipeline kisi bhi broker se chalega.",["Broker API","Python"],None,"API pricing varies by broker; verify."),
 (3,1,"SEBI algo framework hands-on + AI disclosure","SEBI Algo Framework: Hands-On + AI Disclosure","Compliance L3","Audit-log module","Rule fatigue",None,"Circular (4 Feb 2025) in practice: broker-as-principal, exchange Algo-ID registration flow, order-rate threshold, static IP, 2FA, audit logs; RA AI-usage disclosure obligations.","Compliance checklist + audit-log module in code.","Aap apni algo ko compliant tarike se register/route kar paoge.",["Broker portal","Python"],None,"Verified circular; AI-disclosure line DRAFT."),
 (4,2,"Strategy Foundry + strategies #1-#3","Strategy Foundry + Strategies #1-#3","Strategies #1-#3","Common interface","Idea overload","Systematic ORB · Donchian/ATR TF · Bollinger z-score MR","Hypothesis to independent testable layers; cheap spreadsheet screening. #1 Systematic ORB (ATR + vol filter), #2 Donchian/ATR trend-following on index futures, #3 Bollinger z-score mean reversion (stocks).","3 strategies as Python modules with a common interface.","Aap ek strategy factory pattern chala paoge.",["Python","vectorbt/backtrader"],None,None),
 (5,2,"Strategies #4-#5: cross-sectional momentum + pairs trading","Strategies #4-#5: Momentum + Pairs","Strategies #4-#5","Universe handling","Survivorship","Cross-Sectional Momentum · Pairs Trading","#4 Cross-sectional momentum NIFTY 500 (monthly, regime filter, turnover control); #5 Pairs: cointegration (Engle-Granger + Johansen), spread z-score, pair stability, half-life.","Momentum + pairs modules; survivorship-free data.","Aap portfolio-level stat strategies bana paoge.",["Python","statsmodels"],None,None),
 (6,2,"Strategies #6-#7: cash-futures basis + PEAD","Strategies #6-#7: Basis + PEAD","Strategies #6-#7","Event dataset builder","Data quality","Cash-Futures Basis · PEAD","#6 Cash-futures basis/arbitrage & rollover dynamics; #7 Post-Earnings-Announcement Drift with results-review workflow.","Basis monitor + earnings-event dataset builder.","Aap calendar/event-driven edges quantify kar paoge.",["Python","Results data"],None,"Results content: educational, no calls."),
 (7,2,"Strategies #8-#9: gap statistics + LLM sentiment signal","Strategies #8-#9: Gap Stats + LLM Sentiment","Strategies #8-#9","Sentiment pipeline","AI as oracle","Opening Gap Model · LLM Sentiment Filter","#8 Opening gap model (fade vs continuation by gap size/VIX); #9 LLM news/sentiment scoring (structured JSON, guardrails, decay) used as a filter, not a trigger.","Gap stats notebook + Claude sentiment pipeline with logging.","Aap AI ko signal layer ki tarah safely use kar paoge.",["Python","Claude API"],None,"AI output logged; disclosure."),
 (8,3,"Vol surface, IV rank, term structure + strategy #10","Vol Surface, IV Rank, Term Structure + Strategy #10","Strategy #10","Options data loader","Short-vol ka lalach","Delta-Neutral Short Strangle","IV surface, skew, term structure, IV rank/percentile, VIX regimes; #10 delta-neutral short strangle with dynamic hedging + VIX regime filter + hard loss caps.","Options data loader + strangle backtest.","Aap volatility ko trade-able variable ki tarah dekh paoge.",["Python","Options backtester"],None,"NISM ground-truth; margin/risk explained."),
 (9,3,"Strategies #11-#12: calendar/diagonal + expiry-day systematic","Strategies #11-#12: Calendar/Diagonal + 0DTE","Strategies #11-#12","Intraday options backtest","Gamma ka darr","Calendar/Diagonal · Expiry-Day Theta","#11 Calendar/diagonal term-structure spread; #12 expiry-day (0DTE) systematic theta with time-based entries, hard risk caps, no-trade on event days.","Both strategies backtested with intraday options data.","Aap expiry dynamics ko rules mein convert kar paoge.",["Options backtester","Python"],None,"Not 'safe income' language."),
 (10,3,"Strategy #13: volatility regime switching overlay","Strategy #13: Volatility Regime Overlay","Strategy #13","Regime module","Regime lag","Vol Regime Overlay","GARCH/GJR-t forecasts + VIX regimes as sizing/on-off overlay for all strategies; regime transition rules.","Regime module plugged into strategy factory.","Aap regime-aware sizing kar paoge.",["Python (arch)"],None,None),
 (11,3,"Options risk limits + Greeks-based kill rules","Options Risk Limits + Greeks-Based Kill Rules","Risk L3","Greeks monitor","Margin shock",None,"Portfolio Greeks, gamma risk near expiry, margin shocks, Greeks-based limits and auto-flatten rules.","Greeks risk monitor.","Aap options book ka risk real-time samjhoge.",["Python"],None,None),
 (12,4,"Econometrics foundation","Econometrics Foundation","Validation L3","Stat-test toolkit","Spurious correlation",None,"Stationarity (ADF x KPSS), variance ratios, autocorrelation, GARCH, spurious regression defence, Monte Carlo.","Stat-test toolkit applied to all 13 strategies' returns.","Aap 'kya yeh correlation real hai' khud test kar paoge.",["Python","statsmodels"],None,None),
 (13,4,"ML validation + strategy #14: meta-labeling","ML Validation + Strategy #14: Meta-Labeling","Strategy #14 · ML L3","Purged K-fold","Leakage","ML Meta-Labeling","Triple-barrier labels, meta-labeling on a base strategy, uniqueness weights, purged K-fold, walk-forward, CPCV path Sharpes; fractional differentiation.","Meta-labeled version of one T3 strategy.","Aap ML ko leakage-free validate kar paoge.",["Python","scikit-learn"],None,None),
 (14,4,"Overfit accounting","Overfit Accounting","Validation L3","DSR verdict template","Trials ka bhram",None,"Trials ledger, PSR/DSR, minimum track record length, PBO; robustness heatmaps; 'kya yeh edge overfit hai' verdict template.","Overfit report for all 14 strategies.","Aap har strategy ko DSR-adjusted judge kar paoge.",["Python"],None,"'Past performance' on all reports."),
 (15,4,"India cost model + execution simulation","India Cost Model + Execution Simulation","Execution L3","Cost model module","Cost blindness",None,"Brokerage, STT, exchange/SEBI fees, GST, stamp duty (current rates verified in class, never printed); impact cost, slippage model, breakeven; execution sim.","Cost model module; cost-adjusted rerun of all backtests.","Aap real-world cost impact quantify kar paoge.",["Python"],None,"Tax and cost rates verified live in class."),
 (16,5,"Strategy #15: multi-strategy portfolio allocation","Strategy #15: Multi-Strategy Portfolio Allocation","Strategy #15 · Risk L3","Drawdown FSM","Correlation spikes","Multi-Strategy Allocation","Risk parity, fractional Kelly, drawdown-control allocation, correlation of strategy returns, capital allocation across 14 strategies.","Portfolio allocator + drawdown FSM.","Aap strategies ko ek portfolio ki tarah size kar paoge.",["Python"],None,None),
 (17,5,"Execution engine: order manager + kill-switch FSM","Execution Engine: Order Manager + Kill-Switch FSM","Algo L3","Kill-switch FSM","Runaway loop",None,"Order manager, state machine (idle/armed/live/halt), kill-switch triggers (loss, latency, data gap), reconciliation, monitoring + Telegram alerts, audit logging.","Execution engine (paper) with kill-switch.","Aap production-grade execution loop chala paoge.",["Python","Broker API","Telegram bot"],None,"Static IP + audit-log compliance."),
 (18,5,"Live paper deployment via broker API + AI ops","Live Paper Deployment via Broker API + AI Ops","Algo L3","AI ops agent","Deployment jitters","2 strategies (paper-live)","2 strategies paper-live via broker API with Algo-ID; Claude as monitoring/analysis agent (daily report, anomaly flags); backtest to paper to live gates.","2 strategies running paper-live for 2 weeks.","Aap compliant deployment pipeline end-to-end chala chuke honge.",["Broker API","Claude"],None,"Paper only in course; live is the student's own decision."),
 (19,6,"Capstone: own strategy, build, validate, cost, deploy","Capstone: Apni Strategy","Capstone","Peer code review","Perfectionism","Capstone","Student's own idea through the full pipeline; peer code review; mentor checkpoint.","Capstone repo + validation report.","Aapki khud ki strategy launch-ready state mein hogi.",["All"],None,None),
 (20,6,"Present, certify, ongoing research routine","Present, Certify, Research Routine","Capstone","Routine doc","Ownership",None,"Cohort presentation, DSR-honest results, feedback; certificate; weekly research routine template; alumni lab access.","Final presentation + routine doc.","Aap ek running research desk ke saath niklo ge.",[],None,"Certificate carries full disclaimer."),
]
