import { certNo, isCertNo } from "../src/lib/cert/number";
import { evaluate } from "../src/lib/cert/criteria";
let pass = 0, fail = 0; const ok = (n: string, c: boolean, d = "") => { if (c) pass++; else fail++; console.log(`${c ? "  ok  " : "  FAIL"} ${n} ${d}`); };
const no = certNo("foundation", 2026, new Uint8Array([1, 2, 3, 4, 5, 6]));
ok("cert number format 5C-FOUND-2026-XXXXXX", /^5C-FOUND-2026-[A-Z2-9]{6}$/.test(no) && isCertNo(no), no);
ok("no lookalike chars (I L O U 0 1) in base32", !/[ILOU01]/.test(no.split("-")[3]));
ok("advanced code", certNo("advanced", 2027, new Uint8Array(6)).startsWith("5C-ADVAN-2027-"));
ok("invalid numbers rejected", !isCertNo("5C-FOUND-2026-ABC") && !isCertNo("XX-FOUND-2026-ABCDEF") && !isCertNo("5C-FOUND-2026-ABCDE0"));
const base = { sessionsTotal: 20, sessionsComplete: 18, finalPct: 0.6, weeklyAttempted: 3, weeklyTotal: 3, artefactsGraded: [{ grade: "C" }], artefactsRequired: 1, fridayReviews: 3, suspended: false };
ok("all criteria met -> pass band", evaluate(base).ok && evaluate(base).band === "pass");
ok("30/36 -> distinction", evaluate({ ...base, finalPct: 30 / 36 }).band === "distinction");
ok("29/36 -> pass, not distinction", evaluate({ ...base, finalPct: 29 / 36 }).band === "pass");
ok("17/20 sessions fails (needs 18)", !evaluate({ ...base, sessionsComplete: 17 }).ok);
ok("final 59% fails", !evaluate({ ...base, finalPct: 0.59 }).ok);
ok("grade D artefact fails", !evaluate({ ...base, artefactsGraded: [{ grade: "D" }] }).ok);
ok("2 Friday reviews fails", !evaluate({ ...base, fridayReviews: 2 }).ok);
ok("suspended fails and band null", !evaluate({ ...base, suspended: true }).ok && evaluate({ ...base, suspended: true }).band === null);
ok("checklist has 6 items with Hinglish labels, no Devanagari", evaluate(base).items.length === 6 && evaluate(base).items.every((x) => !/[ऀ-ॿ]/.test(x.labelHi)));
console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
