import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";

type OtpType = "recovery" | "magiclink" | "invite" | "email" | "signup" | "email_change";
const OTP_TYPES: OtpType[] = ["recovery", "magiclink", "invite", "email", "signup", "email_change"];

/**
 * Turns a Supabase auth link into a session cookie, then continues to `next`.
 * Accepts either a PKCE `code` (links the app itself requested) or a `token_hash` + `type`
 * (links generated by the Auth admin API, e.g. the first-admin set-password link).
 */
export async function GET(req: NextRequest) {
  const q = req.nextUrl.searchParams;
  const code = q.get("code");
  const tokenHash = q.get("token_hash");
  const type = q.get("type") as OtpType | null;
  const next = q.get("next") ?? "/learn/home";
  const safeNext = next.startsWith("/") && !next.startsWith("//") ? next : "/learn/home";
  if (code || (tokenHash && type && OTP_TYPES.includes(type))) {
    const sb = await createClient();
    const { error } = code
      ? await sb.auth.exchangeCodeForSession(code)
      : await sb.auth.verifyOtp({ token_hash: tokenHash!, type: type! });
    if (!error) return NextResponse.redirect(new URL(safeNext, req.url));
  }
  return NextResponse.redirect(new URL("/learn?error=link", req.url));
}
