import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { appUrl, safeAppPath } from "@/lib/auth/paths";

export const dynamic = "force-dynamic";

type OtpType = "recovery" | "magiclink" | "invite" | "email" | "signup" | "email_change";
const OTP_TYPES: OtpType[] = ["recovery", "magiclink", "invite", "email", "signup", "email_change"];

/**
 * Turns a Supabase auth link into a session cookie, then continues to `next`.
 * Accepts either a PKCE `code` (links the app itself requested) or a `token_hash` + `type`
 * (links generated by the Auth admin API, or an email template that links here with {{ .TokenHash }},
 * which works in any browser). Every redirect is built from the public site URL: behind nginx,
 * req.url is http://127.0.0.1:3001, which is how reset links ended up at https://localhost:3001.
 */
export async function GET(req: NextRequest) {
  const q = req.nextUrl.searchParams;
  const code = q.get("code");
  const tokenHash = q.get("token_hash");
  const type = q.get("type") as OtpType | null;
  const next = safeAppPath(q.get("next"));
  const fail = (reason: string) => {
    const u = new URL(appUrl("/learn"));
    u.searchParams.set("error", "link");
    u.searchParams.set("reason", reason.replace(/[^a-z0-9_]/gi, "").slice(0, 40) || "unknown");
    if (type === "recovery" || next.startsWith("/learn/reset")) u.searchParams.set("kind", "reset");
    return NextResponse.redirect(u);
  };
  if (!code && !(tokenHash && type && OTP_TYPES.includes(type))) return fail("missing_params");
  const sb = await createClient();
  const { data, error } = code
    ? await sb.auth.exchangeCodeForSession(code)
    : await sb.auth.verifyOtp({ token_hash: tokenHash!, type: type! });
  if (error || !data.user) return fail(error?.code ?? "unknown");
  // An email link must not become a side door: self sign-up is open on the Supabase project, so only
  // accounts an invite has activated keep the session.
  const { data: p } = await sb.from("profiles").select("status").eq("id", data.user.id).maybeSingle();
  if (p?.status !== "active") {
    await sb.auth.signOut({ scope: "local" });
    return NextResponse.redirect(appUrl(`/learn?${p?.status === "suspended" ? "suspended" : "inactive"}=1`));
  }
  return NextResponse.redirect(appUrl(next));
}
